
spring:
  application:
    name: Security with Form
  datasource:
    url: jdbc:mysql://localhost:3306/security_form
    username: root
    password: 12x34y56z
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true